version: "3.8"

services:
  app:
    build: .
    ports:
      - "8091:8091"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/noti_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - noti_mongo_data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  noti_mongo_data:
